//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurnSystems {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationBS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationBS() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BurnSystems.LocalizationBS", typeof(LocalizationBS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unerwarteter Header im serialisierten Strom. ähnelt.
        /// </summary>
        internal static string BinaryReader_InvalidHeader {
            get {
                return ResourceManager.GetString("BinaryReader_InvalidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Objekt konnte nicht konvertiert werden: {0} ähnelt.
        /// </summary>
        internal static string BinaryReader_ObjectNotConverted {
            get {
                return ResourceManager.GetString("BinaryReader_ObjectNotConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Objekt konnte nicht konvertiert werden: {0} ähnelt.
        /// </summary>
        internal static string BinaryWriter_ObjectNotConverted {
            get {
                return ResourceManager.GetString("BinaryWriter_ObjectNotConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannter Containertyp ähnelt.
        /// </summary>
        internal static string BinaryWriter_UnknownContainerType {
            get {
                return ResourceManager.GetString("BinaryWriter_UnknownContainerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannter Datentyp ähnelt.
        /// </summary>
        internal static string BinaryWriter_UnknownDataType {
            get {
                return ResourceManager.GetString("BinaryWriter_UnknownDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falscher Datentyp bei der Deserialisierung. Ist: {0}, Soll: {1} ähnelt.
        /// </summary>
        internal static string Composer_WrongTypeFound {
            get {
                return ResourceManager.GetString("Composer_WrongTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datentyp {0} wurde in Datentyp {1} transformiert. ähnelt.
        /// </summary>
        internal static string Composer_WrongTypeTransformed {
            get {
                return ResourceManager.GetString("Composer_WrongTypeTransformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assembly &apos;{0}&apos; konnte nicht geladen werden: {1} ähnelt.
        /// </summary>
        internal static string EnvironmentHelper_AssemblyLoadFailed {
            get {
                return ResourceManager.GetString("EnvironmentHelper_AssemblyLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Assembly &apos;{0}&apos; wurde nicht gefunden. ähnelt.
        /// </summary>
        internal static string EnvironmentHelper_AssemblyNotFound {
            get {
                return ResourceManager.GetString("EnvironmentHelper_AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weder ein Pfad, noch ein starker Name wurde angegeben. ähnelt.
        /// </summary>
        internal static string EnvironmentHelper_PathOrStrongname {
            get {
                return ResourceManager.GetString("EnvironmentHelper_PathOrStrongname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ &apos;{0}&apos; wurde nicht gefunden. ähnelt.
        /// </summary>
        internal static string EnvironmentHelper_TypeNotFound {
            get {
                return ResourceManager.GetString("EnvironmentHelper_TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Methode, die das Attribut &apos;TestMethod&apos; enthält, besitzt mehr als einen Parameter.  ähnelt.
        /// </summary>
        internal static string Executor_InvalidParameterCount {
            get {
                return ResourceManager.GetString("Executor_InvalidParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Klasse, die das Attribut &apos;TestClass&apos; enthält, ist nicht öffentlich. ähnelt.
        /// </summary>
        internal static string Executor_NoPublicClass {
            get {
                return ResourceManager.GetString("Executor_NoPublicClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Methode, die das Attribut &apos;TestMethod&apos; enthält, ist nicht öffentlich. ähnelt.
        /// </summary>
        internal static string Executor_NoPublicMethod {
            get {
                return ResourceManager.GetString("Executor_NoPublicMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Ausnahme wurde beim Schreiben der Logdatei gefangen. ähnelt.
        /// </summary>
        internal static string FileLogProvider_ExceptionCaught {
            get {
                return ResourceManager.GetString("FileLogProvider_ExceptionCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde kein Request durchgeführt. ähnelt.
        /// </summary>
        internal static string HttpRequest_NoRequestExecuted {
            get {
                return ResourceManager.GetString("HttpRequest_NoRequestExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Filter &apos;{0}&apos; ist unbekannt. ähnelt.
        /// </summary>
        internal static string Log_UnknownFilter {
            get {
                return ResourceManager.GetString("Log_UnknownFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbegrenzt ähnelt.
        /// </summary>
        internal static string TimeSpan_MaxValue {
            get {
                return ResourceManager.GetString("TimeSpan_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Attribut &apos;{0}&apos; ausgehend von &apos;{1}&apos; wurde nicht gefunden. ähnelt.
        /// </summary>
        internal static string XmlHelper_AttributeNotFound {
            get {
                return ResourceManager.GetString("XmlHelper_AttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Auswahl &apos;{0}&apos; ausgehend von &apos;{1}&apos; lieferte kein Ergebnis. ähnelt.
        /// </summary>
        internal static string XmlHelper_NodeNotFound {
            get {
                return ResourceManager.GetString("XmlHelper_NodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurden keine Anmeldaten übermittelt. ähnelt.
        /// </summary>
        internal static string XmlWebResponse_CredentialsAreMissing {
            get {
                return ResourceManager.GetString("XmlWebResponse_CredentialsAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Anmeldedaten sind nicht gültig. ähnelt.
        /// </summary>
        internal static string XmlWebResponse_CredentialsAreWrong {
            get {
                return ResourceManager.GetString("XmlWebResponse_CredentialsAreWrong", resourceCulture);
            }
        }
    }
}
