//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurnSystems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationBS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationBS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BurnSystems.LocalizationBS", typeof(LocalizationBS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unerwarteter Header im serialisierten Strom..
        /// </summary>
        internal static string BinaryReader_InvalidHeader {
            get {
                return ResourceManager.GetString("BinaryReader_InvalidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Objekt konnte nicht konvertiert werden: {0}.
        /// </summary>
        internal static string BinaryReader_ObjectNotConverted {
            get {
                return ResourceManager.GetString("BinaryReader_ObjectNotConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Objekt konnte nicht konvertiert werden: {0}.
        /// </summary>
        internal static string BinaryWriter_ObjectNotConverted {
            get {
                return ResourceManager.GetString("BinaryWriter_ObjectNotConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Containertyp.
        /// </summary>
        internal static string BinaryWriter_UnknownContainerType {
            get {
                return ResourceManager.GetString("BinaryWriter_UnknownContainerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Datentyp.
        /// </summary>
        internal static string BinaryWriter_UnknownDataType {
            get {
                return ResourceManager.GetString("BinaryWriter_UnknownDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falscher Datentyp bei der Deserialisierung. Ist: {0}, Soll: {1}.
        /// </summary>
        internal static string Composer_WrongTypeFound {
            get {
                return ResourceManager.GetString("Composer_WrongTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datentyp {0} wurde in Datentyp {1} transformiert..
        /// </summary>
        internal static string Composer_WrongTypeTransformed {
            get {
                return ResourceManager.GetString("Composer_WrongTypeTransformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Assembly &apos;{0}&apos; wurde nicht gefunden..
        /// </summary>
        internal static string EnvironmentHelper_AssemblyNotFound {
            get {
                return ResourceManager.GetString("EnvironmentHelper_AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weder ein Pfad, noch ein starker Name wurde angegeben..
        /// </summary>
        internal static string EnvironmentHelper_PathOrStrongname {
            get {
                return ResourceManager.GetString("EnvironmentHelper_PathOrStrongname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ &apos;{0}&apos; wurde nicht gefunden..
        /// </summary>
        internal static string EnvironmentHelper_TypeNotFound {
            get {
                return ResourceManager.GetString("EnvironmentHelper_TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Methode, die das Attribut &apos;TestMethod&apos; enthält, besitzt mehr als einen Parameter. .
        /// </summary>
        internal static string Executor_InvalidParameterCount {
            get {
                return ResourceManager.GetString("Executor_InvalidParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Klasse, die das Attribut &apos;TestClass&apos; enthält, ist nicht öffentlich..
        /// </summary>
        internal static string Executor_NoPublicClass {
            get {
                return ResourceManager.GetString("Executor_NoPublicClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Methode, die das Attribut &apos;TestMethod&apos; enthält, ist nicht öffentlich..
        /// </summary>
        internal static string Executor_NoPublicMethod {
            get {
                return ResourceManager.GetString("Executor_NoPublicMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Ausnahme wurde beim Schreiben der Logdatei gefangen..
        /// </summary>
        internal static string FileLogProvider_ExceptionCaught {
            get {
                return ResourceManager.GetString("FileLogProvider_ExceptionCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Request durchgeführt..
        /// </summary>
        internal static string HttpRequest_NoRequestExecuted {
            get {
                return ResourceManager.GetString("HttpRequest_NoRequestExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Filter &apos;{0}&apos; ist unbekannt..
        /// </summary>
        internal static string Log_UnknownFilter {
            get {
                return ResourceManager.GetString("Log_UnknownFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbegrenzt.
        /// </summary>
        internal static string TimeSpan_MaxValue {
            get {
                return ResourceManager.GetString("TimeSpan_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Attribut &apos;{0}&apos; ausgehend von &apos;{1}&apos; wurde nicht gefunden..
        /// </summary>
        internal static string XmlHelper_AttributeNotFound {
            get {
                return ResourceManager.GetString("XmlHelper_AttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Auswahl &apos;{0}&apos; ausgehend von &apos;{1}&apos; lieferte kein Ergebnis..
        /// </summary>
        internal static string XmlHelper_NodeNotFound {
            get {
                return ResourceManager.GetString("XmlHelper_NodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden keine Anmeldaten übermittelt..
        /// </summary>
        internal static string XmlWebResponse_CredentialsAreMissing {
            get {
                return ResourceManager.GetString("XmlWebResponse_CredentialsAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anmeldedaten sind nicht gültig..
        /// </summary>
        internal static string XmlWebResponse_CredentialsAreWrong {
            get {
                return ResourceManager.GetString("XmlWebResponse_CredentialsAreWrong", resourceCulture);
            }
        }
    }
}
